globalThis.print = console.log;

(globalThis as unknown as { CharacterStat: unknown }).CharacterStat = {
	ANGER: "ANGER",
	BOREDOM: "BOREDOM",
	DISCOMFORT: "DISCOMFORT",
	ENDURANCE: "ENDURANCE",
	FATIGUE: "FATIGUE",
	FITNESS: "FITNESS",
	FOOD_SICKNESS: "FOOD_SICKNESS",
	HUNGER: "HUNGER",
	IDLENESS: "IDLENESS",
	INTOXICATION: "INTOXICATION",
	MORALE: "MORALE",
	NICOTINE_WITHDRAWAL: "NICOTINE_WITHDRAWAL",
	PAIN: "PAIN",
	PANIC: "PANIC",
	POISON: "POISON",
	SANITY: "SANITY",
	SICKNESS: "SICKNESS",
	STRESS: "STRESS",
	TEMPERATURE: "TEMPERATURE",
	THIRST: "THIRST",
	UNHAPPINESS: "UNHAPPINESS",
	WETNESS: "WETNESS",
	ZOMBIE_FEVER: "ZOMBIE_FEVER",
	ZOMBIE_INFECTION: "ZOMBIE_INFECTION"
};
